spring:
  application:
    name: spring-security-oauth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <your_client_id>
            client-secret: <your_secret>
          google:
            client-id: <your_client_id>
            client-secret: <your_secret>


logging.level.org.springframework.security: TRACE